name: Master

on:
  push:
    branches:
      - master

jobs:
  storybook:
    name: Storybook Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn

      - name: Deploy Storybook to Github Pages
        run: yarn storybook:deploy -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
